-- Exercicio 1
CREATE DATABASE IF NOT EXISTS EXERCISESB22P1;
USE EXERCISESB22P1;

CREATE TABLE countries( 
COUNTRY_ID INT NOT NULL PRIMARY KEY,
COUNTRY_NAME VARCHAR(40) NOT NULL,
REGION_ID INT NOT NULL
);

-- Exercicio 2
CREATE DATABASE IF NOT EXISTS EXERCISESB22P1;
USE EXERCISESB22P1;

CREATE TABLE IF NOT EXISTS countries( 
COUNTRY_ID INT NOT NULL PRIMARY KEY,
COUNTRY_NAME VARCHAR(40) NOT NULL,
REGION_ID INT NOT NULL
);

-- Exercicio 3
CREATE TABLE IF NOT EXISTS dup_countries
LIKE countries;
